
export const portfolioData = [
    //Pet Articles
    {
        Link : "https://miibuddy.com/handy-accessories-for-dogs/",
        MainClass :"box",
        InnerClass :"inner", 
        Imag :"images/Dog Accessories Cover Image.jpg", 
        ImageClass:"image fit",
        Head3 :"An Article on Handy Dog Accessories for Miibuddy",
        Para :"I was tasked to write an article on the handy dog accessories that are available for the Furry pets (Dogs).",
        BtnClass :"button fit style1",
        DataPop:"iframe,1100x600",
        ArticleLink:"https://docs.google.com/document/d/1yuNgjI3MtHOI6fLZI6skhKZYW6zDyjokA-2-SPJ3PdI/edit?usp=sharing",
        LnkName : "View Article"
    },
    {
        Link :"#",
        MainClass :"box",
        InnerClass :"inner", 
        Imag :"images/Dog Clicker Cover Image.jpg", 
        ImageClass:"image fit",
        Head3 :"Article on How to Train Your Dog without a Clicker",
        Para :"This article is about Training Dogs without Clickers I was given the task bu one of my clients and after researching, I wrote this article",
        BtnClass :"button fit style2",
        DataPop:"iframe,1100x600",
        ArticleLink:"https://docs.google.com/document/d/1v2Wf8ZBekv5YT_COCFtlDD4oNNHRzEPE8n1bl1MS_YM/edit?usp=sharing",
        LnkName : "View Article"
    },
    {
        Link :"https://miibuddy.com/multi-use-pet-accessories/",
        MainClass :"box",
        InnerClass :"inner", 
        Imag :"images/Multi-use Accessories Cover Image.jpg", 
        ImageClass:"image fit",
        Head3 :"Article on Multi-Use Pet Accessories",
        Para :"This blog post was on the common Multi-use Pet Accessories that are recommended for pet owners. Here it is;",
        BtnClass :"button fit style3",
        DataPop:"iframe,1100x600",
        ArticleLink:"https://docs.google.com/document/d/1MYlcLK69Kg8ZdP8Uq1SXI8uOy9gpXTlEnJhUKYpShVo/edit?usp=sharing",
        LnkName : "View Article"
    },
    //Painting Articles
    {
        Link :"#",
        MainClass :"box",
        InnerClass :"inner", 
        Imag :"images/Painting Cover Image Three.jpg", 
        ImageClass:"image fit",
        Head3 :"Article on The Influence of art on architecture",
        Para :"There is a big role that art plays in architecture. I took some time to write an article on this two comparative terms for Miicreative",
        BtnClass :"button fit style1",
        DataPop:"iframe,1100x600",
        ArticleLink:"https://docs.google.com/document/d/1l8BBtSD0nlbeMtkxJ6FMRbWnl5b0tIT-UY85OSm9Izs/edit?usp=sharing",
        LnkName : "View Article"
    },
    {
        Link :"https://www.miicreative.com/blogs/painting/perfect-ideas-of-pictures-to-paint",
        MainClass :"box",
        InnerClass :"inner", 
        Imag :"images/Painting Cover Image One.jpg", 
        ImageClass:"image fit",
        Head3 :"Article on A guide on things you need when painting",
        Para :"I love to write articles in the painting niche. Here is one of my previous work. If you have an Online store or Blog that deals with Painting. I'm the guy for your Copywriting tasks.",
        BtnClass :"button fit style2",
        DataPop:"iframe,1100x600",
        ArticleLink:"https://docs.google.com/document/d/1Jg_BaZPqt_yCBZpMG7dTMSFxolKhOVRtE5wNu-7lySo/edit?usp=sharing",
        LnkName : "View Article"
    },
    {
        Link :"",
        MainClass :"box",
        InnerClass :"inner", 
        Imag :"images/Painting Cover Image Two.jpg", 
        ImageClass:"image fit",
        Head3 :"The Hobbies for creative people that are easy to start",
        Para :"Hobbies are cool and effective for one to relax and make good use of leisure. This is why I love writing such are articles to inform people. Check out this article that I did",
        BtnClass :"button fit style1",
        DataPop:"iframe,1100x600",
        ArticleLink:"https://docs.google.com/document/d/1BFRzynO633DTMEhyvDhq7-wLA__6sHaWr4tsmCMVGEk/edit?usp=sharing",
        LnkName : "View Article"
    },
    //Sports Wear
    {
        Link :"",
        MainClass :"box",
        InnerClass :"inner", 
        Imag :"images/Sportswear Image One.jpg", 
        ImageClass:"image fit",
        Head3 :"Article on What Sportswear is needed for outdoor & Indoor activities?",
        Para :"For sports people having the right sportswear is essential. My client gave me a task to write for their online blog. Here is the article to show what I can also do for your blog.",
        BtnClass :"button fit style2",
        DataPop:"iframe,1100x600",
        ArticleLink:"https://docs.google.com/document/d/1ZDKfCYHc6NPf4Lkxa6L8GY_ApK_44UeJUplZG0zFmsY/edit?usp=sharing",
        LnkName : "View Article"
    },
    {
        Link :"#",
        MainClass :"box",
        InnerClass :"inner", 
        Imag :"images/Sportswear Image Two.jpg", 
        ImageClass:"image fit",
        Head3 :"Article on Key features of a school bag for kids",
        Para :"This was an interesting keyword that I was allocated by my client who owns a Sports Wear and Clothing Store. I ultimately did not disappoint",
        BtnClass :"button fit style3",
        DataPop:"iframe,1100x600",
        ArticleLink:"https://docs.google.com/document/d/1IG90_HUSAk_xx7AgOfBIuBYWrTufM_B-RXWQpClsB0Q/edit?usp=sharing",
        LnkName : "View Article"
    },
    {
        Link :"#",
        MainClass :"box",
        InnerClass :"inner", 
        Imag :"images/Sportswear Image Three.jpg", 
        ImageClass:"image fit",
        Head3 :"Article on Pros and cons of physical play",
        Para :"Physical play is important for every person and helps one to be fit. This are some of the pros I wrote about in this article. I also mentioned the cons involved. ",
        BtnClass :"button fit style1",
        DataPop:"iframe,1100x600",
        ArticleLink:"https://docs.google.com/document/d/1XEVOSif4QIuyLOPEhx6l3xpsDg1WPfGavleYGwyYPSk/edit?usp=sharing",
        LnkName : "View Article"
    },
    //Bass Fishing
    {
        Link :"",
        MainClass :"box",
        InnerClass :"inner", 
        Imag :"images/Bass Fishing Image One.jpg", 
        ImageClass:"image fit",
        Head3 :"",
        Para :"",
        BtnClass :"button fit style3",
        DataPop:"iframe,1100x600",
        ArticleLink:"#",
        LnkName : "View Article"
    },
    {
        Link :"",
        MainClass :"box",
        InnerClass :"inner", 
        Imag :"images/Bass Fishing Image Three.jpg", 
        ImageClass:"image fit",
        Head3 :"",
        Para :"We want to check this",
        BtnClass :"button fit style1",
        DataPop:"iframe,1100x600",
        ArticleLink:"#",
        LnkName : "View Article"
    },
    {
        Link :"",
        MainClass :"box",
        InnerClass :"inner", 
        Imag :"images/Bass Fishing Image Two.jpg", 
        ImageClass:"image fit",
        Head3 :"",
        Para :"",
        BtnClass :"button fit style2",
        DataPop:"iframe,1100x600",
        ArticleLink:"#",
        LnkName : "View Article"
    },
    //Fly-Fishing
    {
        Link :"",
        MainClass :"box",
        InnerClass :"inner", 
        Imag :"images/Fly Fishing Image One.jpg", 
        ImageClass:"image fit",
        Head3 :"The Best Fly line For Trout",
        Para :"",
        BtnClass :"button fit style2",
        DataPop:"iframe,1100x600",
        ArticleLink:"https://docs.google.com/document/d/1lWSS5ihwTdG6eH0RmIULGmx-uQYw_Eypt37tnGtO9OQ/edit?usp=sharing",
        LnkName : "View Article"
    },
    {
        Link :"",
        MainClass :"box",
        InnerClass :"inner", 
        Imag :"images/Fly Fishing Image Two.jpg", 
        ImageClass:"image fit",
        Head3 :"The Best fly fishing reel case",
        Para :"",
        BtnClass :"button fit style3",
        DataPop:"iframe,1100x600",
        ArticleLink:"#",
        LnkName : "View Article"
    },
    {
        Link :"#",
        MainClass :"box",
        InnerClass :"inner", 
        Imag :"images/Fly Fishing Image Three.jpg", 
        ImageClass:"image fit",
        Head3 :"The Distance Fly Casting",
        Para :"",
        BtnClass :"button fit style1",
        DataPop:"iframe,1100x600",
        ArticleLink:"https://docs.google.com/document/d/1x1rDNY8TW8PuyCzHDogf8m46_g1XarYYQgUWuiJ88Rw/edit?usp=sharing",
        LnkName : "View Article"
    },
    //Freelancing
    {
        Link :"https://smartonlineworker.home.blog/2021/01/29/a-quick-guide-on-how-to-get-freelancing-jobs-in-2021/",
        MainClass :"box",
        InnerClass :"inner", 
        Imag :"images/Freelancing Images.png", 
        ImageClass:"image fit",
        Head3 :"A Quick Guide on How to Get Freelancing Jobs in 2021",
        Para :"",
        BtnClass :"button fit style1",
        DataPop:"iframe,1200x600",
        ArticleLink:"https://smartonlineworker.home.blog/2021/01/29/a-quick-guide-on-how-to-get-freelancing-jobs-in-2021/",
        LnkName : "View Article"
    },
    {
        Link :"https://ianwriter.medium.com/?p=5f2e4097b8ef",
        MainClass :"box",
        InnerClass :"inner", 
        Imag :"images/Freelancing Images 2.png", 
        ImageClass:"image fit",
        Head3 :"The General Transcription Guide for Freelancers",
        Para :"",
        BtnClass :"button fit style2",
        DataPop:"iframe,1200x600",
        ArticleLink:"https://smartonlineworker.home.blog/2020/10/26/getting-started-in-transcription-as-freelancer/",
        LnkName : "View Article"
    },
    {
        Link :"",
        MainClass :"box",
        InnerClass :"inner", 
        Imag :"images/Freelancing Images 3.jpeg", 
        ImageClass:"image fit",
        Head3 :"5 Ways on How To Make Money Online",
        Para :"",
        BtnClass :"button fit style3",
        DataPop:"iframe,1100x600",
        ArticleLink:"https://smartonlineworker.home.blog/2020/08/25/5-proven-ways-of-making-money-online-in-kenya/",
        LnkName : "View Article"
    }
]
